
out : example03-func.o example03-main.o
	gcc -o out example03-func.c example03-main.o

example03-func.o :
	gcc -c example03-func.c

example03-main.o :
	gcc -c example03-main.c

clean :
	rm -rf example03-func.o example03-main.o out
